services:
  wallets_postgres:
    image: postgres:latest
    container_name: wallets_postgres
    command: -p ${POSTGRES_PORT:?err}
    expose:
      - ${POSTGRES_PORT:?err}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data

  wallets_redis:
    image: redis:latest
    container_name: wallets_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  wallets_app:
    container_name: wallets_app
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - wallets_postgres
      - wallets_redis

  wallets_celery_worker:
    container_name: wallets_celery_worker
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - wallets_postgres
      - wallets_redis

volumes:
  postgres_data:
  redis_data: